// <auto-generated />
using System;
using Fitness.Backend.Domain.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness.Backend.Domain.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230227173038_LessonUserManyToMany")]
    partial class LessonUserManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest",
                            PostalCode = 1011
                        },
                        new
                        {
                            Id = 2,
                            Name = "Debrecen",
                            PostalCode = 4024
                        },
                        new
                        {
                            Id = 3,
                            Name = "Miskolc",
                            PostalCode = 3525
                        },
                        new
                        {
                            Id = 4,
                            Name = "Szeged",
                            PostalCode = 6720
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pécs",
                            PostalCode = 7621
                        },
                        new
                        {
                            Id = 6,
                            Name = "Győr",
                            PostalCode = 9021
                        },
                        new
                        {
                            Id = 7,
                            Name = "Nyíregyháza",
                            PostalCode = 4400
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kecskemét",
                            PostalCode = 6000
                        },
                        new
                        {
                            Id = 9,
                            Name = "Székesfehérvár",
                            PostalCode = 8000
                        },
                        new
                        {
                            Id = 10,
                            Name = "Szombathely",
                            PostalCode = 9700
                        },
                        new
                        {
                            Id = 11,
                            Name = "Szolnok",
                            PostalCode = 5000
                        },
                        new
                        {
                            Id = 12,
                            Name = "Tatabánya",
                            PostalCode = 2800
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kaposvár",
                            PostalCode = 7400
                        },
                        new
                        {
                            Id = 14,
                            Name = "Érd",
                            PostalCode = 2030
                        },
                        new
                        {
                            Id = 15,
                            Name = "Veszprém",
                            PostalCode = 8200
                        },
                        new
                        {
                            Id = 16,
                            Name = "Békéscsaba",
                            PostalCode = 5600
                        },
                        new
                        {
                            Id = 17,
                            Name = "Zalaegerszeg",
                            PostalCode = 8900
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sopron",
                            PostalCode = 9400
                        },
                        new
                        {
                            Id = 19,
                            Name = "Eger",
                            PostalCode = 3300
                        },
                        new
                        {
                            Id = 20,
                            Name = "Nagykanizsa",
                            PostalCode = 8800
                        });
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("LessonUser", b =>
                {
                    b.Property<int>("LessonsId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LessonsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("LessonUser");
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.Lesson", b =>
                {
                    b.HasOne("Fitness.Backend.Application.DataContracts.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.Sport", b =>
                {
                    b.HasOne("Fitness.Backend.Application.DataContracts.Models.Instructor", null)
                        .WithMany("Sports")
                        .HasForeignKey("InstructorId");
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.User", b =>
                {
                    b.HasOne("Fitness.Backend.Application.DataContracts.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("LessonUser", b =>
                {
                    b.HasOne("Fitness.Backend.Application.DataContracts.Models.Lesson", null)
                        .WithMany()
                        .HasForeignKey("LessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fitness.Backend.Application.DataContracts.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fitness.Backend.Application.DataContracts.Models.Instructor", b =>
                {
                    b.Navigation("Sports");
                });
#pragma warning restore 612, 618
        }
    }
}
